{
 "title": "ESP32 Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Chip Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_chip_model{endpoint=\"esp32_temperature\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Core Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_core_version{endpoint=\"esp32_temperature\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nbr of Core",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_chip_cores{endpoint=\"esp32_temperature\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mac Address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wifi_mac_address{endpoint=\"esp32_temperature\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ESP32 Ip",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wifi_local_ip{endpoint=\"esp32_temperature\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SDK Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_sdk_version{endpoint=\"esp32_temperature\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chip Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_flash_chip_size{endpoint=\"esp32_temperature\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sketch Size Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(system_sketch_size{endpoint=\"esp32_temperature\"} * 100) / (system_sketch_size{endpoint=\"esp32_temperature\"} +system_free_sketch_space{endpoint=\"esp32_temperature\"} )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime_total{endpoint=\"esp32_temperature\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wifi Signal Strength",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "wifi_rssi{endpoint=\"esp32_temperature\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Available Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "system_free_heap{endpoint=\"esp32_temperature\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dht_humidity{endpoint=\"esp32_temperature\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "dht_temperature{endpoint=\"esp32_temperature\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}